# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import generated_proto.analitic_pb2 as analitic__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analitic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub(object):
    """===== Сервис
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFines = channel.unary_unary(
                '/analytics.v1.AnalyticsService/GetFines',
                request_serializer=analitic__pb2.FinesRequest.SerializeToString,
                response_deserializer=analitic__pb2.FinesResponse.FromString,
                _registered_method=True)
        self.GetEvac = channel.unary_unary(
                '/analytics.v1.AnalyticsService/GetEvac',
                request_serializer=analitic__pb2.EvacRequest.SerializeToString,
                response_deserializer=analitic__pb2.EvacResponse.FromString,
                _registered_method=True)
        self.GetDtp = channel.unary_unary(
                '/analytics.v1.AnalyticsService/GetDtp',
                request_serializer=analitic__pb2.DtpRequest.SerializeToString,
                response_deserializer=analitic__pb2.DtpResponse.FromString,
                _registered_method=True)
        self.Compare = channel.unary_unary(
                '/analytics.v1.AnalyticsService/Compare',
                request_serializer=analitic__pb2.CompareRequest.SerializeToString,
                response_deserializer=analitic__pb2.CompareResponse.FromString,
                _registered_method=True)
        self.GetForecast = channel.unary_unary(
                '/analytics.v1.AnalyticsService/GetForecast',
                request_serializer=analitic__pb2.GetForecastRequest.SerializeToString,
                response_deserializer=analitic__pb2.GetForecastResponse.FromString,
                _registered_method=True)
        self.ImportBytes = channel.unary_unary(
                '/analytics.v1.AnalyticsService/ImportBytes',
                request_serializer=analitic__pb2.ImportBytesRequest.SerializeToString,
                response_deserializer=analitic__pb2.ImportBytesResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """===== Сервис
    """

    def GetFines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvac(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDtp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetForecast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFines,
                    request_deserializer=analitic__pb2.FinesRequest.FromString,
                    response_serializer=analitic__pb2.FinesResponse.SerializeToString,
            ),
            'GetEvac': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvac,
                    request_deserializer=analitic__pb2.EvacRequest.FromString,
                    response_serializer=analitic__pb2.EvacResponse.SerializeToString,
            ),
            'GetDtp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDtp,
                    request_deserializer=analitic__pb2.DtpRequest.FromString,
                    response_serializer=analitic__pb2.DtpResponse.SerializeToString,
            ),
            'Compare': grpc.unary_unary_rpc_method_handler(
                    servicer.Compare,
                    request_deserializer=analitic__pb2.CompareRequest.FromString,
                    response_serializer=analitic__pb2.CompareResponse.SerializeToString,
            ),
            'GetForecast': grpc.unary_unary_rpc_method_handler(
                    servicer.GetForecast,
                    request_deserializer=analitic__pb2.GetForecastRequest.FromString,
                    response_serializer=analitic__pb2.GetForecastResponse.SerializeToString,
            ),
            'ImportBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportBytes,
                    request_deserializer=analitic__pb2.ImportBytesRequest.FromString,
                    response_serializer=analitic__pb2.ImportBytesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.v1.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.v1.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """===== Сервис
    """

    @staticmethod
    def GetFines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.v1.AnalyticsService/GetFines',
            analitic__pb2.FinesRequest.SerializeToString,
            analitic__pb2.FinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvac(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.v1.AnalyticsService/GetEvac',
            analitic__pb2.EvacRequest.SerializeToString,
            analitic__pb2.EvacResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDtp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.v1.AnalyticsService/GetDtp',
            analitic__pb2.DtpRequest.SerializeToString,
            analitic__pb2.DtpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.v1.AnalyticsService/Compare',
            analitic__pb2.CompareRequest.SerializeToString,
            analitic__pb2.CompareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetForecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.v1.AnalyticsService/GetForecast',
            analitic__pb2.GetForecastRequest.SerializeToString,
            analitic__pb2.GetForecastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.v1.AnalyticsService/ImportBytes',
            analitic__pb2.ImportBytesRequest.SerializeToString,
            analitic__pb2.ImportBytesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
