# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import generated_proto.content_pb2 as content__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in content_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNews = channel.unary_unary(
                '/content.ContentService/CreateNews',
                request_serializer=content__pb2.CreateNewsRequest.SerializeToString,
                response_deserializer=content__pb2.CreateNewsResponse.FromString,
                _registered_method=True)
        self.GetNews = channel.unary_unary(
                '/content.ContentService/GetNews',
                request_serializer=content__pb2.GetNewsRequest.SerializeToString,
                response_deserializer=content__pb2.GetNewsResponse.FromString,
                _registered_method=True)
        self.UpdateNews = channel.unary_unary(
                '/content.ContentService/UpdateNews',
                request_serializer=content__pb2.UpdateNewsRequest.SerializeToString,
                response_deserializer=content__pb2.UpdateNewsResponse.FromString,
                _registered_method=True)
        self.DeleteNews = channel.unary_unary(
                '/content.ContentService/DeleteNews',
                request_serializer=content__pb2.DeleteNewsRequest.SerializeToString,
                response_deserializer=content__pb2.DeleteNewsResponse.FromString,
                _registered_method=True)
        self.ListNews = channel.unary_unary(
                '/content.ContentService/ListNews',
                request_serializer=content__pb2.ListNewsRequest.SerializeToString,
                response_deserializer=content__pb2.ListNewsResponse.FromString,
                _registered_method=True)
        self.GetCountNews = channel.unary_unary(
                '/content.ContentService/GetCountNews',
                request_serializer=content__pb2.Empty.SerializeToString,
                response_deserializer=content__pb2.GetCountNewsResponse.FromString,
                _registered_method=True)
        self.CreateVacancy = channel.unary_unary(
                '/content.ContentService/CreateVacancy',
                request_serializer=content__pb2.CreateVacancyRequest.SerializeToString,
                response_deserializer=content__pb2.CreateVacancyResponse.FromString,
                _registered_method=True)
        self.GetVacancy = channel.unary_unary(
                '/content.ContentService/GetVacancy',
                request_serializer=content__pb2.GetVacancyRequest.SerializeToString,
                response_deserializer=content__pb2.GetVacancyResponse.FromString,
                _registered_method=True)
        self.UpdateVacancy = channel.unary_unary(
                '/content.ContentService/UpdateVacancy',
                request_serializer=content__pb2.UpdateVacancyRequest.SerializeToString,
                response_deserializer=content__pb2.UpdateVacancyResponse.FromString,
                _registered_method=True)
        self.DeleteVacancy = channel.unary_unary(
                '/content.ContentService/DeleteVacancy',
                request_serializer=content__pb2.DeleteVacancyRequest.SerializeToString,
                response_deserializer=content__pb2.DeleteVacancyResponse.FromString,
                _registered_method=True)
        self.ListAllVacancies = channel.unary_unary(
                '/content.ContentService/ListAllVacancies',
                request_serializer=content__pb2.ListVacanciesRequest.SerializeToString,
                response_deserializer=content__pb2.ListVacanciesResponse.FromString,
                _registered_method=True)
        self.ListActiveVacancies = channel.unary_unary(
                '/content.ContentService/ListActiveVacancies',
                request_serializer=content__pb2.ListVacanciesRequest.SerializeToString,
                response_deserializer=content__pb2.ListVacanciesResponse.FromString,
                _registered_method=True)
        self.GetCountVacancies = channel.unary_unary(
                '/content.ContentService/GetCountVacancies',
                request_serializer=content__pb2.Empty.SerializeToString,
                response_deserializer=content__pb2.GetCountVacanciesResponse.FromString,
                _registered_method=True)
        self.CreateDocument = channel.unary_unary(
                '/content.ContentService/CreateDocument',
                request_serializer=content__pb2.CreateDocumentRequest.SerializeToString,
                response_deserializer=content__pb2.CreateDocumentResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/content.ContentService/GetDocument',
                request_serializer=content__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=content__pb2.GetDocumentResponse.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/content.ContentService/ListDocuments',
                request_serializer=content__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=content__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/content.ContentService/DeleteDocument',
                request_serializer=content__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=content__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)
        self.CreateContact = channel.unary_unary(
                '/content.ContentService/CreateContact',
                request_serializer=content__pb2.CreateContactRequest.SerializeToString,
                response_deserializer=content__pb2.Contact.FromString,
                _registered_method=True)
        self.GetContact = channel.unary_unary(
                '/content.ContentService/GetContact',
                request_serializer=content__pb2.ContactId.SerializeToString,
                response_deserializer=content__pb2.Contact.FromString,
                _registered_method=True)
        self.ListContacts = channel.unary_unary(
                '/content.ContentService/ListContacts',
                request_serializer=content__pb2.ContactListRequest.SerializeToString,
                response_deserializer=content__pb2.ContactListResponse.FromString,
                _registered_method=True)
        self.UpdateContact = channel.unary_unary(
                '/content.ContentService/UpdateContact',
                request_serializer=content__pb2.Contact.SerializeToString,
                response_deserializer=content__pb2.Contact.FromString,
                _registered_method=True)
        self.DeleteContact = channel.unary_unary(
                '/content.ContentService/DeleteContact',
                request_serializer=content__pb2.ContactId.SerializeToString,
                response_deserializer=content__pb2.DeleteContactResponse.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/content.ContentService/CreateProject',
                request_serializer=content__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=content__pb2.CreateProjectResponse.FromString,
                _registered_method=True)
        self.GetProject = channel.unary_unary(
                '/content.ContentService/GetProject',
                request_serializer=content__pb2.GetProjectRequest.SerializeToString,
                response_deserializer=content__pb2.GetProjectResponse.FromString,
                _registered_method=True)
        self.UpdateProject = channel.unary_unary(
                '/content.ContentService/UpdateProject',
                request_serializer=content__pb2.UpdateProjectRequest.SerializeToString,
                response_deserializer=content__pb2.UpdateProjectResponse.FromString,
                _registered_method=True)
        self.DeleteProject = channel.unary_unary(
                '/content.ContentService/DeleteProject',
                request_serializer=content__pb2.DeleteProjectRequest.SerializeToString,
                response_deserializer=content__pb2.DeleteProjectResponse.FromString,
                _registered_method=True)
        self.ListProjects = channel.unary_unary(
                '/content.ContentService/ListProjects',
                request_serializer=content__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=content__pb2.ListProjectsResponse.FromString,
                _registered_method=True)


class ContentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNews(self, request, context):
        """News
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCountNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVacancy(self, request, context):
        """Vacancy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVacancy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVacancy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVacancy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllVacancies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActiveVacancies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCountVacancies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDocument(self, request, context):
        """Documents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateContact(self, request, context):
        """Conntact
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """Project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNews': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNews,
                    request_deserializer=content__pb2.CreateNewsRequest.FromString,
                    response_serializer=content__pb2.CreateNewsResponse.SerializeToString,
            ),
            'GetNews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNews,
                    request_deserializer=content__pb2.GetNewsRequest.FromString,
                    response_serializer=content__pb2.GetNewsResponse.SerializeToString,
            ),
            'UpdateNews': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNews,
                    request_deserializer=content__pb2.UpdateNewsRequest.FromString,
                    response_serializer=content__pb2.UpdateNewsResponse.SerializeToString,
            ),
            'DeleteNews': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNews,
                    request_deserializer=content__pb2.DeleteNewsRequest.FromString,
                    response_serializer=content__pb2.DeleteNewsResponse.SerializeToString,
            ),
            'ListNews': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNews,
                    request_deserializer=content__pb2.ListNewsRequest.FromString,
                    response_serializer=content__pb2.ListNewsResponse.SerializeToString,
            ),
            'GetCountNews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCountNews,
                    request_deserializer=content__pb2.Empty.FromString,
                    response_serializer=content__pb2.GetCountNewsResponse.SerializeToString,
            ),
            'CreateVacancy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVacancy,
                    request_deserializer=content__pb2.CreateVacancyRequest.FromString,
                    response_serializer=content__pb2.CreateVacancyResponse.SerializeToString,
            ),
            'GetVacancy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVacancy,
                    request_deserializer=content__pb2.GetVacancyRequest.FromString,
                    response_serializer=content__pb2.GetVacancyResponse.SerializeToString,
            ),
            'UpdateVacancy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVacancy,
                    request_deserializer=content__pb2.UpdateVacancyRequest.FromString,
                    response_serializer=content__pb2.UpdateVacancyResponse.SerializeToString,
            ),
            'DeleteVacancy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVacancy,
                    request_deserializer=content__pb2.DeleteVacancyRequest.FromString,
                    response_serializer=content__pb2.DeleteVacancyResponse.SerializeToString,
            ),
            'ListAllVacancies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllVacancies,
                    request_deserializer=content__pb2.ListVacanciesRequest.FromString,
                    response_serializer=content__pb2.ListVacanciesResponse.SerializeToString,
            ),
            'ListActiveVacancies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActiveVacancies,
                    request_deserializer=content__pb2.ListVacanciesRequest.FromString,
                    response_serializer=content__pb2.ListVacanciesResponse.SerializeToString,
            ),
            'GetCountVacancies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCountVacancies,
                    request_deserializer=content__pb2.Empty.FromString,
                    response_serializer=content__pb2.GetCountVacanciesResponse.SerializeToString,
            ),
            'CreateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDocument,
                    request_deserializer=content__pb2.CreateDocumentRequest.FromString,
                    response_serializer=content__pb2.CreateDocumentResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=content__pb2.GetDocumentRequest.FromString,
                    response_serializer=content__pb2.GetDocumentResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=content__pb2.ListDocumentsRequest.FromString,
                    response_serializer=content__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=content__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=content__pb2.DeleteDocumentResponse.SerializeToString,
            ),
            'CreateContact': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateContact,
                    request_deserializer=content__pb2.CreateContactRequest.FromString,
                    response_serializer=content__pb2.Contact.SerializeToString,
            ),
            'GetContact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContact,
                    request_deserializer=content__pb2.ContactId.FromString,
                    response_serializer=content__pb2.Contact.SerializeToString,
            ),
            'ListContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContacts,
                    request_deserializer=content__pb2.ContactListRequest.FromString,
                    response_serializer=content__pb2.ContactListResponse.SerializeToString,
            ),
            'UpdateContact': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateContact,
                    request_deserializer=content__pb2.Contact.FromString,
                    response_serializer=content__pb2.Contact.SerializeToString,
            ),
            'DeleteContact': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteContact,
                    request_deserializer=content__pb2.ContactId.FromString,
                    response_serializer=content__pb2.DeleteContactResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=content__pb2.CreateProjectRequest.FromString,
                    response_serializer=content__pb2.CreateProjectResponse.SerializeToString,
            ),
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=content__pb2.GetProjectRequest.FromString,
                    response_serializer=content__pb2.GetProjectResponse.SerializeToString,
            ),
            'UpdateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProject,
                    request_deserializer=content__pb2.UpdateProjectRequest.FromString,
                    response_serializer=content__pb2.UpdateProjectResponse.SerializeToString,
            ),
            'DeleteProject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProject,
                    request_deserializer=content__pb2.DeleteProjectRequest.FromString,
                    response_serializer=content__pb2.DeleteProjectResponse.SerializeToString,
            ),
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=content__pb2.ListProjectsRequest.FromString,
                    response_serializer=content__pb2.ListProjectsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'content.ContentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('content.ContentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/CreateNews',
            content__pb2.CreateNewsRequest.SerializeToString,
            content__pb2.CreateNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/GetNews',
            content__pb2.GetNewsRequest.SerializeToString,
            content__pb2.GetNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/UpdateNews',
            content__pb2.UpdateNewsRequest.SerializeToString,
            content__pb2.UpdateNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/DeleteNews',
            content__pb2.DeleteNewsRequest.SerializeToString,
            content__pb2.DeleteNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/ListNews',
            content__pb2.ListNewsRequest.SerializeToString,
            content__pb2.ListNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCountNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/GetCountNews',
            content__pb2.Empty.SerializeToString,
            content__pb2.GetCountNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVacancy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/CreateVacancy',
            content__pb2.CreateVacancyRequest.SerializeToString,
            content__pb2.CreateVacancyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVacancy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/GetVacancy',
            content__pb2.GetVacancyRequest.SerializeToString,
            content__pb2.GetVacancyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVacancy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/UpdateVacancy',
            content__pb2.UpdateVacancyRequest.SerializeToString,
            content__pb2.UpdateVacancyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVacancy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/DeleteVacancy',
            content__pb2.DeleteVacancyRequest.SerializeToString,
            content__pb2.DeleteVacancyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllVacancies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/ListAllVacancies',
            content__pb2.ListVacanciesRequest.SerializeToString,
            content__pb2.ListVacanciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActiveVacancies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/ListActiveVacancies',
            content__pb2.ListVacanciesRequest.SerializeToString,
            content__pb2.ListVacanciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCountVacancies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/GetCountVacancies',
            content__pb2.Empty.SerializeToString,
            content__pb2.GetCountVacanciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/CreateDocument',
            content__pb2.CreateDocumentRequest.SerializeToString,
            content__pb2.CreateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/GetDocument',
            content__pb2.GetDocumentRequest.SerializeToString,
            content__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/ListDocuments',
            content__pb2.ListDocumentsRequest.SerializeToString,
            content__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/DeleteDocument',
            content__pb2.DeleteDocumentRequest.SerializeToString,
            content__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/CreateContact',
            content__pb2.CreateContactRequest.SerializeToString,
            content__pb2.Contact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/GetContact',
            content__pb2.ContactId.SerializeToString,
            content__pb2.Contact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/ListContacts',
            content__pb2.ContactListRequest.SerializeToString,
            content__pb2.ContactListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/UpdateContact',
            content__pb2.Contact.SerializeToString,
            content__pb2.Contact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/DeleteContact',
            content__pb2.ContactId.SerializeToString,
            content__pb2.DeleteContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/CreateProject',
            content__pb2.CreateProjectRequest.SerializeToString,
            content__pb2.CreateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/GetProject',
            content__pb2.GetProjectRequest.SerializeToString,
            content__pb2.GetProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/UpdateProject',
            content__pb2.UpdateProjectRequest.SerializeToString,
            content__pb2.UpdateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/DeleteProject',
            content__pb2.DeleteProjectRequest.SerializeToString,
            content__pb2.DeleteProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content.ContentService/ListProjects',
            content__pb2.ListProjectsRequest.SerializeToString,
            content__pb2.ListProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
