// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/location.proto

package location

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_proto_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{1}
}

func (x *CreateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateItemRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_proto_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{2}
}

func (x *CreateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_proto_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_proto_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_proto_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateItemRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_proto_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_proto_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_proto_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_proto_location_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{9}
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_proto_location_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{10}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type TrafficLight struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address          string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	YearInstallation int32                  `protobuf:"varint,4,opt,name=year_installation,json=yearInstallation,proto3" json:"year_installation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrafficLight) Reset() {
	*x = TrafficLight{}
	mi := &file_proto_location_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficLight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficLight) ProtoMessage() {}

func (x *TrafficLight) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficLight.ProtoReflect.Descriptor instead.
func (*TrafficLight) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{11}
}

func (x *TrafficLight) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TrafficLight) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TrafficLight) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TrafficLight) GetYearInstallation() int32 {
	if x != nil {
		return x.YearInstallation
	}
	return 0
}

type CreateTrafficLightRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Address          string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	YearInstallation int32                  `protobuf:"varint,3,opt,name=year_installation,json=yearInstallation,proto3" json:"year_installation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTrafficLightRequest) Reset() {
	*x = CreateTrafficLightRequest{}
	mi := &file_proto_location_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrafficLightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrafficLightRequest) ProtoMessage() {}

func (x *CreateTrafficLightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrafficLightRequest.ProtoReflect.Descriptor instead.
func (*CreateTrafficLightRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTrafficLightRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateTrafficLightRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTrafficLightRequest) GetYearInstallation() int32 {
	if x != nil {
		return x.YearInstallation
	}
	return 0
}

type CreateTrafficLightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrafficLight  *TrafficLight          `protobuf:"bytes,1,opt,name=traffic_light,json=trafficLight,proto3" json:"traffic_light,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrafficLightResponse) Reset() {
	*x = CreateTrafficLightResponse{}
	mi := &file_proto_location_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrafficLightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrafficLightResponse) ProtoMessage() {}

func (x *CreateTrafficLightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrafficLightResponse.ProtoReflect.Descriptor instead.
func (*CreateTrafficLightResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTrafficLightResponse) GetTrafficLight() *TrafficLight {
	if x != nil {
		return x.TrafficLight
	}
	return nil
}

type GetTrafficLightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrafficLightRequest) Reset() {
	*x = GetTrafficLightRequest{}
	mi := &file_proto_location_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrafficLightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrafficLightRequest) ProtoMessage() {}

func (x *GetTrafficLightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrafficLightRequest.ProtoReflect.Descriptor instead.
func (*GetTrafficLightRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{14}
}

func (x *GetTrafficLightRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTrafficLightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrafficLight  *TrafficLight          `protobuf:"bytes,1,opt,name=traffic_light,json=trafficLight,proto3" json:"traffic_light,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrafficLightResponse) Reset() {
	*x = GetTrafficLightResponse{}
	mi := &file_proto_location_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrafficLightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrafficLightResponse) ProtoMessage() {}

func (x *GetTrafficLightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrafficLightResponse.ProtoReflect.Descriptor instead.
func (*GetTrafficLightResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{15}
}

func (x *GetTrafficLightResponse) GetTrafficLight() *TrafficLight {
	if x != nil {
		return x.TrafficLight
	}
	return nil
}

type UpdateTrafficLightRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address          string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	YearInstallation int32                  `protobuf:"varint,4,opt,name=year_installation,json=yearInstallation,proto3" json:"year_installation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateTrafficLightRequest) Reset() {
	*x = UpdateTrafficLightRequest{}
	mi := &file_proto_location_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrafficLightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrafficLightRequest) ProtoMessage() {}

func (x *UpdateTrafficLightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrafficLightRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrafficLightRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateTrafficLightRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTrafficLightRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateTrafficLightRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateTrafficLightRequest) GetYearInstallation() int32 {
	if x != nil {
		return x.YearInstallation
	}
	return 0
}

type UpdateTrafficLightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrafficLight  *TrafficLight          `protobuf:"bytes,1,opt,name=traffic_light,json=trafficLight,proto3" json:"traffic_light,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrafficLightResponse) Reset() {
	*x = UpdateTrafficLightResponse{}
	mi := &file_proto_location_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrafficLightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrafficLightResponse) ProtoMessage() {}

func (x *UpdateTrafficLightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrafficLightResponse.ProtoReflect.Descriptor instead.
func (*UpdateTrafficLightResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateTrafficLightResponse) GetTrafficLight() *TrafficLight {
	if x != nil {
		return x.TrafficLight
	}
	return nil
}

type DeleteTrafficLightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTrafficLightRequest) Reset() {
	*x = DeleteTrafficLightRequest{}
	mi := &file_proto_location_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTrafficLightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrafficLightRequest) ProtoMessage() {}

func (x *DeleteTrafficLightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrafficLightRequest.ProtoReflect.Descriptor instead.
func (*DeleteTrafficLightRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteTrafficLightRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTrafficLightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTrafficLightResponse) Reset() {
	*x = DeleteTrafficLightResponse{}
	mi := &file_proto_location_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTrafficLightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrafficLightResponse) ProtoMessage() {}

func (x *DeleteTrafficLightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrafficLightResponse.ProtoReflect.Descriptor instead.
func (*DeleteTrafficLightResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteTrafficLightResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListTrafficLightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrafficLightsRequest) Reset() {
	*x = ListTrafficLightsRequest{}
	mi := &file_proto_location_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrafficLightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrafficLightsRequest) ProtoMessage() {}

func (x *ListTrafficLightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrafficLightsRequest.ProtoReflect.Descriptor instead.
func (*ListTrafficLightsRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{20}
}

type ListTrafficLightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrafficLights []*TrafficLight        `protobuf:"bytes,1,rep,name=traffic_lights,json=trafficLights,proto3" json:"traffic_lights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrafficLightsResponse) Reset() {
	*x = ListTrafficLightsResponse{}
	mi := &file_proto_location_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrafficLightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrafficLightsResponse) ProtoMessage() {}

func (x *ListTrafficLightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrafficLightsResponse.ProtoReflect.Descriptor instead.
func (*ListTrafficLightsResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{21}
}

func (x *ListTrafficLightsResponse) GetTrafficLights() []*TrafficLight {
	if x != nil {
		return x.TrafficLights
	}
	return nil
}

var File_proto_location_proto protoreflect.FileDescriptor

const file_proto_location_proto_rawDesc = "" +
	"\n" +
	"\x14proto/location.proto\x12\blocation\"X\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"U\n" +
	"\x11CreateItemRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"8\n" +
	"\x12CreateItemResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.location.ItemR\x04item\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x0fGetItemResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.location.ItemR\x04item\"e\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"8\n" +
	"\x12UpdateItemResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.location.ItemR\x04item\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\".\n" +
	"\x12DeleteItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x12\n" +
	"\x10ListItemsRequest\"9\n" +
	"\x11ListItemsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.location.ItemR\x05items\"y\n" +
	"\fTrafficLight\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12+\n" +
	"\x11year_installation\x18\x04 \x01(\x05R\x10yearInstallation\"v\n" +
	"\x19CreateTrafficLightRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12+\n" +
	"\x11year_installation\x18\x03 \x01(\x05R\x10yearInstallation\"Y\n" +
	"\x1aCreateTrafficLightResponse\x12;\n" +
	"\rtraffic_light\x18\x01 \x01(\v2\x16.location.TrafficLightR\ftrafficLight\"(\n" +
	"\x16GetTrafficLightRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"V\n" +
	"\x17GetTrafficLightResponse\x12;\n" +
	"\rtraffic_light\x18\x01 \x01(\v2\x16.location.TrafficLightR\ftrafficLight\"\x86\x01\n" +
	"\x19UpdateTrafficLightRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12+\n" +
	"\x11year_installation\x18\x04 \x01(\x05R\x10yearInstallation\"Y\n" +
	"\x1aUpdateTrafficLightResponse\x12;\n" +
	"\rtraffic_light\x18\x01 \x01(\v2\x16.location.TrafficLightR\ftrafficLight\"+\n" +
	"\x19DeleteTrafficLightRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"6\n" +
	"\x1aDeleteTrafficLightResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1a\n" +
	"\x18ListTrafficLightsRequest\"Z\n" +
	"\x19ListTrafficLightsResponse\x12=\n" +
	"\x0etraffic_lights\x18\x01 \x03(\v2\x16.location.TrafficLightR\rtrafficLights2\xc7\x06\n" +
	"\vItemService\x12G\n" +
	"\n" +
	"CreateItem\x12\x1b.location.CreateItemRequest\x1a\x1c.location.CreateItemResponse\x12>\n" +
	"\aGetItem\x12\x18.location.GetItemRequest\x1a\x19.location.GetItemResponse\x12G\n" +
	"\n" +
	"UpdateItem\x12\x1b.location.UpdateItemRequest\x1a\x1c.location.UpdateItemResponse\x12G\n" +
	"\n" +
	"DeleteItem\x12\x1b.location.DeleteItemRequest\x1a\x1c.location.DeleteItemResponse\x12D\n" +
	"\tListItems\x12\x1a.location.ListItemsRequest\x1a\x1b.location.ListItemsResponse\x12_\n" +
	"\x12CreateTrafficLight\x12#.location.CreateTrafficLightRequest\x1a$.location.CreateTrafficLightResponse\x12V\n" +
	"\x0fGetTrafficLight\x12 .location.GetTrafficLightRequest\x1a!.location.GetTrafficLightResponse\x12_\n" +
	"\x12UpdateTrafficLight\x12#.location.UpdateTrafficLightRequest\x1a$.location.UpdateTrafficLightResponse\x12_\n" +
	"\x12DeleteTrafficLight\x12#.location.DeleteTrafficLightRequest\x1a$.location.DeleteTrafficLightResponse\x12\\\n" +
	"\x11ListTrafficLights\x12\".location.ListTrafficLightsRequest\x1a#.location.ListTrafficLightsResponseB\x12Z\x10./proto;locationb\x06proto3"

var (
	file_proto_location_proto_rawDescOnce sync.Once
	file_proto_location_proto_rawDescData []byte
)

func file_proto_location_proto_rawDescGZIP() []byte {
	file_proto_location_proto_rawDescOnce.Do(func() {
		file_proto_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_location_proto_rawDesc), len(file_proto_location_proto_rawDesc)))
	})
	return file_proto_location_proto_rawDescData
}

var file_proto_location_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_location_proto_goTypes = []any{
	(*Item)(nil),                       // 0: location.Item
	(*CreateItemRequest)(nil),          // 1: location.CreateItemRequest
	(*CreateItemResponse)(nil),         // 2: location.CreateItemResponse
	(*GetItemRequest)(nil),             // 3: location.GetItemRequest
	(*GetItemResponse)(nil),            // 4: location.GetItemResponse
	(*UpdateItemRequest)(nil),          // 5: location.UpdateItemRequest
	(*UpdateItemResponse)(nil),         // 6: location.UpdateItemResponse
	(*DeleteItemRequest)(nil),          // 7: location.DeleteItemRequest
	(*DeleteItemResponse)(nil),         // 8: location.DeleteItemResponse
	(*ListItemsRequest)(nil),           // 9: location.ListItemsRequest
	(*ListItemsResponse)(nil),          // 10: location.ListItemsResponse
	(*TrafficLight)(nil),               // 11: location.TrafficLight
	(*CreateTrafficLightRequest)(nil),  // 12: location.CreateTrafficLightRequest
	(*CreateTrafficLightResponse)(nil), // 13: location.CreateTrafficLightResponse
	(*GetTrafficLightRequest)(nil),     // 14: location.GetTrafficLightRequest
	(*GetTrafficLightResponse)(nil),    // 15: location.GetTrafficLightResponse
	(*UpdateTrafficLightRequest)(nil),  // 16: location.UpdateTrafficLightRequest
	(*UpdateTrafficLightResponse)(nil), // 17: location.UpdateTrafficLightResponse
	(*DeleteTrafficLightRequest)(nil),  // 18: location.DeleteTrafficLightRequest
	(*DeleteTrafficLightResponse)(nil), // 19: location.DeleteTrafficLightResponse
	(*ListTrafficLightsRequest)(nil),   // 20: location.ListTrafficLightsRequest
	(*ListTrafficLightsResponse)(nil),  // 21: location.ListTrafficLightsResponse
}
var file_proto_location_proto_depIdxs = []int32{
	0,  // 0: location.CreateItemResponse.item:type_name -> location.Item
	0,  // 1: location.GetItemResponse.item:type_name -> location.Item
	0,  // 2: location.UpdateItemResponse.item:type_name -> location.Item
	0,  // 3: location.ListItemsResponse.items:type_name -> location.Item
	11, // 4: location.CreateTrafficLightResponse.traffic_light:type_name -> location.TrafficLight
	11, // 5: location.GetTrafficLightResponse.traffic_light:type_name -> location.TrafficLight
	11, // 6: location.UpdateTrafficLightResponse.traffic_light:type_name -> location.TrafficLight
	11, // 7: location.ListTrafficLightsResponse.traffic_lights:type_name -> location.TrafficLight
	1,  // 8: location.ItemService.CreateItem:input_type -> location.CreateItemRequest
	3,  // 9: location.ItemService.GetItem:input_type -> location.GetItemRequest
	5,  // 10: location.ItemService.UpdateItem:input_type -> location.UpdateItemRequest
	7,  // 11: location.ItemService.DeleteItem:input_type -> location.DeleteItemRequest
	9,  // 12: location.ItemService.ListItems:input_type -> location.ListItemsRequest
	12, // 13: location.ItemService.CreateTrafficLight:input_type -> location.CreateTrafficLightRequest
	14, // 14: location.ItemService.GetTrafficLight:input_type -> location.GetTrafficLightRequest
	16, // 15: location.ItemService.UpdateTrafficLight:input_type -> location.UpdateTrafficLightRequest
	18, // 16: location.ItemService.DeleteTrafficLight:input_type -> location.DeleteTrafficLightRequest
	20, // 17: location.ItemService.ListTrafficLights:input_type -> location.ListTrafficLightsRequest
	2,  // 18: location.ItemService.CreateItem:output_type -> location.CreateItemResponse
	4,  // 19: location.ItemService.GetItem:output_type -> location.GetItemResponse
	6,  // 20: location.ItemService.UpdateItem:output_type -> location.UpdateItemResponse
	8,  // 21: location.ItemService.DeleteItem:output_type -> location.DeleteItemResponse
	10, // 22: location.ItemService.ListItems:output_type -> location.ListItemsResponse
	13, // 23: location.ItemService.CreateTrafficLight:output_type -> location.CreateTrafficLightResponse
	15, // 24: location.ItemService.GetTrafficLight:output_type -> location.GetTrafficLightResponse
	17, // 25: location.ItemService.UpdateTrafficLight:output_type -> location.UpdateTrafficLightResponse
	19, // 26: location.ItemService.DeleteTrafficLight:output_type -> location.DeleteTrafficLightResponse
	21, // 27: location.ItemService.ListTrafficLights:output_type -> location.ListTrafficLightsResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_location_proto_init() }
func file_proto_location_proto_init() {
	if File_proto_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_location_proto_rawDesc), len(file_proto_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_location_proto_goTypes,
		DependencyIndexes: file_proto_location_proto_depIdxs,
		MessageInfos:      file_proto_location_proto_msgTypes,
	}.Build()
	File_proto_location_proto = out.File
	file_proto_location_proto_goTypes = nil
	file_proto_location_proto_depIdxs = nil
}
