// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: analitic.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetFines_FullMethodName    = "/analytics.v1.AnalyticsService/GetFines"
	AnalyticsService_GetEvac_FullMethodName     = "/analytics.v1.AnalyticsService/GetEvac"
	AnalyticsService_GetDtp_FullMethodName      = "/analytics.v1.AnalyticsService/GetDtp"
	AnalyticsService_Compare_FullMethodName     = "/analytics.v1.AnalyticsService/Compare"
	AnalyticsService_GetForecast_FullMethodName = "/analytics.v1.AnalyticsService/GetForecast"
	AnalyticsService_ImportBytes_FullMethodName = "/analytics.v1.AnalyticsService/ImportBytes"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===== Сервис
type AnalyticsServiceClient interface {
	GetFines(ctx context.Context, in *FinesRequest, opts ...grpc.CallOption) (*FinesResponse, error)
	GetEvac(ctx context.Context, in *EvacRequest, opts ...grpc.CallOption) (*EvacResponse, error)
	GetDtp(ctx context.Context, in *DtpRequest, opts ...grpc.CallOption) (*DtpResponse, error)
	Compare(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResponse, error)
	GetForecast(ctx context.Context, in *GetForecastRequest, opts ...grpc.CallOption) (*GetForecastResponse, error)
	ImportBytes(ctx context.Context, in *ImportBytesRequest, opts ...grpc.CallOption) (*ImportBytesResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetFines(ctx context.Context, in *FinesRequest, opts ...grpc.CallOption) (*FinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetFines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetEvac(ctx context.Context, in *EvacRequest, opts ...grpc.CallOption) (*EvacResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvacResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetEvac_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDtp(ctx context.Context, in *DtpRequest, opts ...grpc.CallOption) (*DtpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DtpResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDtp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) Compare(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_Compare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetForecast(ctx context.Context, in *GetForecastRequest, opts ...grpc.CallOption) (*GetForecastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetForecastResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetForecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) ImportBytes(ctx context.Context, in *ImportBytesRequest, opts ...grpc.CallOption) (*ImportBytesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportBytesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_ImportBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
//
// ===== Сервис
type AnalyticsServiceServer interface {
	GetFines(context.Context, *FinesRequest) (*FinesResponse, error)
	GetEvac(context.Context, *EvacRequest) (*EvacResponse, error)
	GetDtp(context.Context, *DtpRequest) (*DtpResponse, error)
	Compare(context.Context, *CompareRequest) (*CompareResponse, error)
	GetForecast(context.Context, *GetForecastRequest) (*GetForecastResponse, error)
	ImportBytes(context.Context, *ImportBytesRequest) (*ImportBytesResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetFines(context.Context, *FinesRequest) (*FinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFines not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetEvac(context.Context, *EvacRequest) (*EvacResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvac not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDtp(context.Context, *DtpRequest) (*DtpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDtp not implemented")
}
func (UnimplementedAnalyticsServiceServer) Compare(context.Context, *CompareRequest) (*CompareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compare not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetForecast(context.Context, *GetForecastRequest) (*GetForecastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForecast not implemented")
}
func (UnimplementedAnalyticsServiceServer) ImportBytes(context.Context, *ImportBytesRequest) (*ImportBytesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportBytes not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetFines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetFines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetFines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetFines(ctx, req.(*FinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetEvac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvacRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetEvac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetEvac_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetEvac(ctx, req.(*EvacRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDtp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDtp(ctx, req.(*DtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_Compare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).Compare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_Compare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).Compare(ctx, req.(*CompareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetForecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetForecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetForecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetForecast(ctx, req.(*GetForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_ImportBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportBytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).ImportBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_ImportBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).ImportBytes(ctx, req.(*ImportBytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFines",
			Handler:    _AnalyticsService_GetFines_Handler,
		},
		{
			MethodName: "GetEvac",
			Handler:    _AnalyticsService_GetEvac_Handler,
		},
		{
			MethodName: "GetDtp",
			Handler:    _AnalyticsService_GetDtp_Handler,
		},
		{
			MethodName: "Compare",
			Handler:    _AnalyticsService_Compare_Handler,
		},
		{
			MethodName: "GetForecast",
			Handler:    _AnalyticsService_GetForecast_Handler,
		},
		{
			MethodName: "ImportBytes",
			Handler:    _AnalyticsService_ImportBytes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analitic.proto",
}
