// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: analitic.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromDate      string                 `protobuf:"bytes,1,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"` // ISO: YYYY-MM-DD
	ToDate        string                 `protobuf:"bytes,2,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_analitic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{0}
}

func (x *DateRange) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *DateRange) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupBy       string                 `protobuf:"bytes,1,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Admin         bool                   `protobuf:"varint,2,opt,name=admin,proto3" json:"admin,omitempty"` // true = админ (с деньгами)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_analitic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{1}
}

func (x *Meta) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

func (x *Meta) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type Point struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Один из ключей периода: для штрафов/эвакуаций используем dt,
	// для МВД — period (первое число месяца).
	//
	// Types that are valid to be assigned to Bucket:
	//
	//	*Point_Dt
	//	*Point_Period
	Bucket        isPoint_Bucket `protobuf_oneof:"bucket"`
	Value         int64          `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_analitic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetBucket() isPoint_Bucket {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *Point) GetDt() string {
	if x != nil {
		if x, ok := x.Bucket.(*Point_Dt); ok {
			return x.Dt
		}
	}
	return ""
}

func (x *Point) GetPeriod() string {
	if x != nil {
		if x, ok := x.Bucket.(*Point_Period); ok {
			return x.Period
		}
	}
	return ""
}

func (x *Point) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type isPoint_Bucket interface {
	isPoint_Bucket()
}

type Point_Dt struct {
	Dt string `protobuf:"bytes,1,opt,name=dt,proto3,oneof"` // YYYY-MM-DD
}

type Point_Period struct {
	Period string `protobuf:"bytes,2,opt,name=period,proto3,oneof"` // YYYY-MM-01
}

func (*Point_Dt) isPoint_Bucket() {}

func (*Point_Period) isPoint_Bucket() {}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_analitic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{3}
}

func (x *Series) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Aggregates struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Суммы по сериям: key = имя серии (например "evacuations")
	Sum map[string]int64 `protobuf:"bytes,1,rep,name=sum,proto3" json:"sum,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Средние по сериям (используется только для trucks_on_line и т.п.)
	Avg           map[string]float64 `protobuf:"bytes,2,rep,name=avg,proto3" json:"avg,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aggregates) Reset() {
	*x = Aggregates{}
	mi := &file_analitic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aggregates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aggregates) ProtoMessage() {}

func (x *Aggregates) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aggregates.ProtoReflect.Descriptor instead.
func (*Aggregates) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{4}
}

func (x *Aggregates) GetSum() map[string]int64 {
	if x != nil {
		return x.Sum
	}
	return nil
}

func (x *Aggregates) GetAvg() map[string]float64 {
	if x != nil {
		return x.Avg
	}
	return nil
}

type KPI struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionRate float64                `protobuf:"fixed64,1,opt,name=collection_rate,json=collectionRate,proto3" json:"collection_rate,omitempty"` // штрафы: sum(collected)/sum(imposed)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KPI) Reset() {
	*x = KPI{}
	mi := &file_analitic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KPI) ProtoMessage() {}

func (x *KPI) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KPI.ProtoReflect.Descriptor instead.
func (*KPI) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{5}
}

func (x *KPI) GetCollectionRate() float64 {
	if x != nil {
		return x.CollectionRate
	}
	return 0
}

// ===== Ответы виджетов
type FinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        map[string]*Series     `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // violations_delta, rulings_delta, (admin) imposed_delta, collected_delta
	Aggregates    *Aggregates            `protobuf:"bytes,2,opt,name=aggregates,proto3" json:"aggregates,omitempty"`                                                                   // sum.*
	Kpi           *KPI                   `protobuf:"bytes,3,opt,name=kpi,proto3" json:"kpi,omitempty"`                                                                                 // пустой, если гость
	Meta          *Meta                  `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`                                                                               // group_by, admin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinesResponse) Reset() {
	*x = FinesResponse{}
	mi := &file_analitic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinesResponse) ProtoMessage() {}

func (x *FinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinesResponse.ProtoReflect.Descriptor instead.
func (*FinesResponse) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{6}
}

func (x *FinesResponse) GetSeries() map[string]*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *FinesResponse) GetAggregates() *Aggregates {
	if x != nil {
		return x.Aggregates
	}
	return nil
}

func (x *FinesResponse) GetKpi() *KPI {
	if x != nil {
		return x.Kpi
	}
	return nil
}

func (x *FinesResponse) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type EvacResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        map[string]*Series     `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // trucks_on_line, trips, evacuations, (admin) impound_income
	Aggregates    *Aggregates            `protobuf:"bytes,2,opt,name=aggregates,proto3" json:"aggregates,omitempty"`                                                                   // sum.*, avg.trucks_on_line
	Meta          *Meta                  `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvacResponse) Reset() {
	*x = EvacResponse{}
	mi := &file_analitic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvacResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvacResponse) ProtoMessage() {}

func (x *EvacResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvacResponse.ProtoReflect.Descriptor instead.
func (*EvacResponse) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{7}
}

func (x *EvacResponse) GetSeries() map[string]*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *EvacResponse) GetAggregates() *Aggregates {
	if x != nil {
		return x.Aggregates
	}
	return nil
}

func (x *EvacResponse) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        map[string]*Series     `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // injured_accidents, fatalities, injured_persons
	Aggregates    *Aggregates            `protobuf:"bytes,2,opt,name=aggregates,proto3" json:"aggregates,omitempty"`                                                                   // sum.*
	Meta          *Meta                  `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`                                                                               // group_by=MONTH
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtpResponse) Reset() {
	*x = DtpResponse{}
	mi := &file_analitic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtpResponse) ProtoMessage() {}

func (x *DtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtpResponse.ProtoReflect.Descriptor instead.
func (*DtpResponse) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{8}
}

func (x *DtpResponse) GetSeries() map[string]*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *DtpResponse) GetAggregates() *Aggregates {
	if x != nil {
		return x.Aggregates
	}
	return nil
}

func (x *DtpResponse) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// ===== Сравнение периодов (A vs B)
type PeriodAgg struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	FromDate string                 `protobuf:"bytes,1,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"` // YYYY-MM-DD
	ToDate   string                 `protobuf:"bytes,2,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	Sum      int64                  `protobuf:"varint,3,opt,name=sum,proto3" json:"sum,omitempty"`
	// Для дневных рядов avg = sum / days; для МВД (месяц) = null → передаём 0 и is_set=false
	Avg           float64 `protobuf:"fixed64,4,opt,name=avg,proto3" json:"avg,omitempty"`
	AvgSet        bool    `protobuf:"varint,5,opt,name=avg_set,json=avgSet,proto3" json:"avg_set,omitempty"` // true если avg задан
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodAgg) Reset() {
	*x = PeriodAgg{}
	mi := &file_analitic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodAgg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodAgg) ProtoMessage() {}

func (x *PeriodAgg) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodAgg.ProtoReflect.Descriptor instead.
func (*PeriodAgg) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{9}
}

func (x *PeriodAgg) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *PeriodAgg) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *PeriodAgg) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *PeriodAgg) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *PeriodAgg) GetAvgSet() bool {
	if x != nil {
		return x.AvgSet
	}
	return false
}

type Diff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abs           int64                  `protobuf:"varint,1,opt,name=abs,proto3" json:"abs,omitempty"`  // sumA - sumB
	Rel           float64                `protobuf:"fixed64,2,opt,name=rel,proto3" json:"rel,omitempty"` // (sumA - sumB) / sumB; если sumB=0 → rel_set=false
	RelSet        bool                   `protobuf:"varint,3,opt,name=rel_set,json=relSet,proto3" json:"rel_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diff) Reset() {
	*x = Diff{}
	mi := &file_analitic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diff) ProtoMessage() {}

func (x *Diff) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diff.ProtoReflect.Descriptor instead.
func (*Diff) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{10}
}

func (x *Diff) GetAbs() int64 {
	if x != nil {
		return x.Abs
	}
	return 0
}

func (x *Diff) GetRel() float64 {
	if x != nil {
		return x.Rel
	}
	return 0
}

func (x *Diff) GetRelSet() bool {
	if x != nil {
		return x.RelSet
	}
	return false
}

type CompareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"` // evacuations | fatalities | violations_delta | ...
	PeriodA       *PeriodAgg             `protobuf:"bytes,2,opt,name=period_a,json=periodA,proto3" json:"period_a,omitempty"`
	PeriodB       *PeriodAgg             `protobuf:"bytes,3,opt,name=period_b,json=periodB,proto3" json:"period_b,omitempty"`
	Diff          *Diff                  `protobuf:"bytes,4,opt,name=diff,proto3" json:"diff,omitempty"`
	Admin         bool                   `protobuf:"varint,5,opt,name=admin,proto3" json:"admin,omitempty"` // режим
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareResponse) Reset() {
	*x = CompareResponse{}
	mi := &file_analitic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareResponse) ProtoMessage() {}

func (x *CompareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareResponse.ProtoReflect.Descriptor instead.
func (*CompareResponse) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{11}
}

func (x *CompareResponse) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *CompareResponse) GetPeriodA() *PeriodAgg {
	if x != nil {
		return x.PeriodA
	}
	return nil
}

func (x *CompareResponse) GetPeriodB() *PeriodAgg {
	if x != nil {
		return x.PeriodB
	}
	return nil
}

func (x *CompareResponse) GetDiff() *Diff {
	if x != nil {
		return x.Diff
	}
	return nil
}

func (x *CompareResponse) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

// ===== Запросы
type FinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *DateRange             `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	GroupBy       string                 `protobuf:"bytes,2,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"` // day|week|month
	Public        bool                   `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`                 // true = гость
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinesRequest) Reset() {
	*x = FinesRequest{}
	mi := &file_analitic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinesRequest) ProtoMessage() {}

func (x *FinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinesRequest.ProtoReflect.Descriptor instead.
func (*FinesRequest) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{12}
}

func (x *FinesRequest) GetRange() *DateRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *FinesRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

func (x *FinesRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

type EvacRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *DateRange             `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	GroupBy       string                 `protobuf:"bytes,2,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Public        bool                   `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvacRequest) Reset() {
	*x = EvacRequest{}
	mi := &file_analitic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvacRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvacRequest) ProtoMessage() {}

func (x *EvacRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvacRequest.ProtoReflect.Descriptor instead.
func (*EvacRequest) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{13}
}

func (x *EvacRequest) GetRange() *DateRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *EvacRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

func (x *EvacRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

type DtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *DateRange             `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"` // group_by игнорируется, всегда month
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtpRequest) Reset() {
	*x = DtpRequest{}
	mi := &file_analitic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtpRequest) ProtoMessage() {}

func (x *DtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtpRequest.ProtoReflect.Descriptor instead.
func (*DtpRequest) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{14}
}

func (x *DtpRequest) GetRange() *DateRange {
	if x != nil {
		return x.Range
	}
	return nil
}

type CompareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"` // белый список на сервере
	PeriodA       *DateRange             `protobuf:"bytes,2,opt,name=period_a,json=periodA,proto3" json:"period_a,omitempty"`
	PeriodB       *DateRange             `protobuf:"bytes,3,opt,name=period_b,json=periodB,proto3" json:"period_b,omitempty"`
	Public        bool                   `protobuf:"varint,4,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareRequest) Reset() {
	*x = CompareRequest{}
	mi := &file_analitic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareRequest) ProtoMessage() {}

func (x *CompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareRequest.ProtoReflect.Descriptor instead.
func (*CompareRequest) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{15}
}

func (x *CompareRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *CompareRequest) GetPeriodA() *DateRange {
	if x != nil {
		return x.PeriodA
	}
	return nil
}

func (x *CompareRequest) GetPeriodB() *DateRange {
	if x != nil {
		return x.PeriodB
	}
	return nil
}

func (x *CompareRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

type FilePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"` // например "ЦОДД.xlsx" или "mvd_data.csv"
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`   // бинарное содержимое файла
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePayload) Reset() {
	*x = FilePayload{}
	mi := &file_analitic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePayload) ProtoMessage() {}

func (x *FilePayload) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePayload.ProtoReflect.Descriptor instead.
func (*FilePayload) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{16}
}

func (x *FilePayload) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FilePayload) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ImportBytesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Files []*FilePayload         `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	// Стратегия: "append" (вставка/обновление), "replace" (полная замена таблиц)
	Mode          string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // default: "append"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportBytesRequest) Reset() {
	*x = ImportBytesRequest{}
	mi := &file_analitic_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportBytesRequest) ProtoMessage() {}

func (x *ImportBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportBytesRequest.ProtoReflect.Descriptor instead.
func (*ImportBytesRequest) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{17}
}

func (x *ImportBytesRequest) GetFiles() []*FilePayload {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ImportBytesRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ImportBytesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                              // "ok"
	SummaryJson   string                 `protobuf:"bytes,2,opt,name=summary_json,json=summaryJson,proto3" json:"summary_json,omitempty"` // JSON со статистикой rows/range/warnings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportBytesResponse) Reset() {
	*x = ImportBytesResponse{}
	mi := &file_analitic_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportBytesResponse) ProtoMessage() {}

func (x *ImportBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportBytesResponse.ProtoReflect.Descriptor instead.
func (*ImportBytesResponse) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{18}
}

func (x *ImportBytesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ImportBytesResponse) GetSummaryJson() string {
	if x != nil {
		return x.SummaryJson
	}
	return ""
}

type GetForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"` // "injured_accidents" или "evacuations"
	Horizon       int32                  `protobuf:"varint,4,opt,name=horizon,proto3" json:"horizon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastRequest) Reset() {
	*x = GetForecastRequest{}
	mi := &file_analitic_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastRequest) ProtoMessage() {}

func (x *GetForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastRequest.ProtoReflect.Descriptor instead.
func (*GetForecastRequest) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{19}
}

func (x *GetForecastRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *GetForecastRequest) GetHorizon() int32 {
	if x != nil {
		return x.Horizon
	}
	return 0
}

type GetForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrainRange    *DateRange             `protobuf:"bytes,1,opt,name=train_range,json=trainRange,proto3" json:"train_range,omitempty"`    // Фактический диапазон данных, использованных для обучения
	Freq          string                 `protobuf:"bytes,2,opt,name=freq,proto3" json:"freq,omitempty"`                                  // "month" или "day"
	Forecast      []*ForecastPoint       `protobuf:"bytes,3,rep,name=forecast,proto3" json:"forecast,omitempty"`                          // Прогнозируемые точки
	LastHistory   []*HistoryPoint        `protobuf:"bytes,4,rep,name=last_history,json=lastHistory,proto3" json:"last_history,omitempty"` // Последние точки из истории
	Meta          *MetaInfo              `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`                                  // Мета-информация
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastResponse) Reset() {
	*x = GetForecastResponse{}
	mi := &file_analitic_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastResponse) ProtoMessage() {}

func (x *GetForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastResponse.ProtoReflect.Descriptor instead.
func (*GetForecastResponse) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{20}
}

func (x *GetForecastResponse) GetTrainRange() *DateRange {
	if x != nil {
		return x.TrainRange
	}
	return nil
}

func (x *GetForecastResponse) GetFreq() string {
	if x != nil {
		return x.Freq
	}
	return ""
}

func (x *GetForecastResponse) GetForecast() []*ForecastPoint {
	if x != nil {
		return x.Forecast
	}
	return nil
}

func (x *GetForecastResponse) GetLastHistory() []*HistoryPoint {
	if x != nil {
		return x.LastHistory
	}
	return nil
}

func (x *GetForecastResponse) GetMeta() *MetaInfo {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Сообщение для одной точки прогноза
type ForecastPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ds            string                 `protobuf:"bytes,1,opt,name=ds,proto3" json:"ds,omitempty"`                                  // Дата в формате "YYYY-MM-DD"
	Yhat          float64                `protobuf:"fixed64,2,opt,name=yhat,proto3" json:"yhat,omitempty"`                            // Прогнозируемое значение
	YhatLower     float64                `protobuf:"fixed64,3,opt,name=yhat_lower,json=yhatLower,proto3" json:"yhat_lower,omitempty"` // Нижняя граница доверительного интервала
	YhatUpper     float64                `protobuf:"fixed64,4,opt,name=yhat_upper,json=yhatUpper,proto3" json:"yhat_upper,omitempty"` // Верхняя граница доверительного интервала
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastPoint) Reset() {
	*x = ForecastPoint{}
	mi := &file_analitic_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastPoint) ProtoMessage() {}

func (x *ForecastPoint) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastPoint.ProtoReflect.Descriptor instead.
func (*ForecastPoint) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{21}
}

func (x *ForecastPoint) GetDs() string {
	if x != nil {
		return x.Ds
	}
	return ""
}

func (x *ForecastPoint) GetYhat() float64 {
	if x != nil {
		return x.Yhat
	}
	return 0
}

func (x *ForecastPoint) GetYhatLower() float64 {
	if x != nil {
		return x.YhatLower
	}
	return 0
}

func (x *ForecastPoint) GetYhatUpper() float64 {
	if x != nil {
		return x.YhatUpper
	}
	return 0
}

// Сообщение для одной точки истории
type HistoryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ds            string                 `protobuf:"bytes,1,opt,name=ds,proto3" json:"ds,omitempty"` // Дата в формате "YYYY-MM-DD"
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"` // Фактическое значение
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryPoint) Reset() {
	*x = HistoryPoint{}
	mi := &file_analitic_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryPoint) ProtoMessage() {}

func (x *HistoryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryPoint.ProtoReflect.Descriptor instead.
func (*HistoryPoint) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{22}
}

func (x *HistoryPoint) GetDs() string {
	if x != nil {
		return x.Ds
	}
	return ""
}

func (x *HistoryPoint) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Сообщение для мета-информации
type MetaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`    // Использованная метрика
	Horizon       int32                  `protobuf:"varint,2,opt,name=horizon,proto3" json:"horizon,omitempty"` // Горизонт прогноза
	Cv            *CrossValidationInfo   `protobuf:"bytes,3,opt,name=cv,proto3,oneof" json:"cv,omitempty"`      // Информация о кросс-валидации (опционально, если debug=true)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaInfo) Reset() {
	*x = MetaInfo{}
	mi := &file_analitic_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaInfo) ProtoMessage() {}

func (x *MetaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaInfo.ProtoReflect.Descriptor instead.
func (*MetaInfo) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{23}
}

func (x *MetaInfo) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *MetaInfo) GetHorizon() int32 {
	if x != nil {
		return x.Horizon
	}
	return 0
}

func (x *MetaInfo) GetCv() *CrossValidationInfo {
	if x != nil {
		return x.Cv
	}
	return nil
}

// Сообщение для информации о кросс-валидации
type CrossValidationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mae           float64                `protobuf:"fixed64,1,opt,name=mae,proto3" json:"mae,omitempty"`     // Средняя абсолютная ошибка
	Smape         float64                `protobuf:"fixed64,2,opt,name=smape,proto3" json:"smape,omitempty"` // Симметричное среднее абсолютное процентное отклонение
	Mape          float64                `protobuf:"fixed64,3,opt,name=mape,proto3" json:"mape,omitempty"`   // Среднее абсолютное процентное отклонение (опционально, как в описании)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossValidationInfo) Reset() {
	*x = CrossValidationInfo{}
	mi := &file_analitic_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossValidationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossValidationInfo) ProtoMessage() {}

func (x *CrossValidationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_analitic_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossValidationInfo.ProtoReflect.Descriptor instead.
func (*CrossValidationInfo) Descriptor() ([]byte, []int) {
	return file_analitic_proto_rawDescGZIP(), []int{24}
}

func (x *CrossValidationInfo) GetMae() float64 {
	if x != nil {
		return x.Mae
	}
	return 0
}

func (x *CrossValidationInfo) GetSmape() float64 {
	if x != nil {
		return x.Smape
	}
	return 0
}

func (x *CrossValidationInfo) GetMape() float64 {
	if x != nil {
		return x.Mape
	}
	return 0
}

var File_analitic_proto protoreflect.FileDescriptor

const file_analitic_proto_rawDesc = "" +
	"\n" +
	"\x0eanalitic.proto\x12\fanalytics.v1\"A\n" +
	"\tDateRange\x12\x1b\n" +
	"\tfrom_date\x18\x01 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x02 \x01(\tR\x06toDate\"7\n" +
	"\x04Meta\x12\x19\n" +
	"\bgroup_by\x18\x01 \x01(\tR\agroupBy\x12\x14\n" +
	"\x05admin\x18\x02 \x01(\bR\x05admin\"S\n" +
	"\x05Point\x12\x10\n" +
	"\x02dt\x18\x01 \x01(\tH\x00R\x02dt\x12\x18\n" +
	"\x06period\x18\x02 \x01(\tH\x00R\x06period\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05valueB\b\n" +
	"\x06bucket\"5\n" +
	"\x06Series\x12+\n" +
	"\x06points\x18\x01 \x03(\v2\x13.analytics.v1.PointR\x06points\"\xe6\x01\n" +
	"\n" +
	"Aggregates\x123\n" +
	"\x03sum\x18\x01 \x03(\v2!.analytics.v1.Aggregates.SumEntryR\x03sum\x123\n" +
	"\x03avg\x18\x02 \x03(\v2!.analytics.v1.Aggregates.AvgEntryR\x03avg\x1a6\n" +
	"\bSumEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a6\n" +
	"\bAvgEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\".\n" +
	"\x03KPI\x12'\n" +
	"\x0fcollection_rate\x18\x01 \x01(\x01R\x0ecollectionRate\"\xa8\x02\n" +
	"\rFinesResponse\x12?\n" +
	"\x06series\x18\x01 \x03(\v2'.analytics.v1.FinesResponse.SeriesEntryR\x06series\x128\n" +
	"\n" +
	"aggregates\x18\x02 \x01(\v2\x18.analytics.v1.AggregatesR\n" +
	"aggregates\x12#\n" +
	"\x03kpi\x18\x03 \x01(\v2\x11.analytics.v1.KPIR\x03kpi\x12&\n" +
	"\x04meta\x18\x04 \x01(\v2\x12.analytics.v1.MetaR\x04meta\x1aO\n" +
	"\vSeriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.analytics.v1.SeriesR\x05value:\x028\x01\"\x81\x02\n" +
	"\fEvacResponse\x12>\n" +
	"\x06series\x18\x01 \x03(\v2&.analytics.v1.EvacResponse.SeriesEntryR\x06series\x128\n" +
	"\n" +
	"aggregates\x18\x02 \x01(\v2\x18.analytics.v1.AggregatesR\n" +
	"aggregates\x12&\n" +
	"\x04meta\x18\x03 \x01(\v2\x12.analytics.v1.MetaR\x04meta\x1aO\n" +
	"\vSeriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.analytics.v1.SeriesR\x05value:\x028\x01\"\xff\x01\n" +
	"\vDtpResponse\x12=\n" +
	"\x06series\x18\x01 \x03(\v2%.analytics.v1.DtpResponse.SeriesEntryR\x06series\x128\n" +
	"\n" +
	"aggregates\x18\x02 \x01(\v2\x18.analytics.v1.AggregatesR\n" +
	"aggregates\x12&\n" +
	"\x04meta\x18\x03 \x01(\v2\x12.analytics.v1.MetaR\x04meta\x1aO\n" +
	"\vSeriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.analytics.v1.SeriesR\x05value:\x028\x01\"~\n" +
	"\tPeriodAgg\x12\x1b\n" +
	"\tfrom_date\x18\x01 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x02 \x01(\tR\x06toDate\x12\x10\n" +
	"\x03sum\x18\x03 \x01(\x03R\x03sum\x12\x10\n" +
	"\x03avg\x18\x04 \x01(\x01R\x03avg\x12\x17\n" +
	"\aavg_set\x18\x05 \x01(\bR\x06avgSet\"C\n" +
	"\x04Diff\x12\x10\n" +
	"\x03abs\x18\x01 \x01(\x03R\x03abs\x12\x10\n" +
	"\x03rel\x18\x02 \x01(\x01R\x03rel\x12\x17\n" +
	"\arel_set\x18\x03 \x01(\bR\x06relSet\"\xcf\x01\n" +
	"\x0fCompareResponse\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x122\n" +
	"\bperiod_a\x18\x02 \x01(\v2\x17.analytics.v1.PeriodAggR\aperiodA\x122\n" +
	"\bperiod_b\x18\x03 \x01(\v2\x17.analytics.v1.PeriodAggR\aperiodB\x12&\n" +
	"\x04diff\x18\x04 \x01(\v2\x12.analytics.v1.DiffR\x04diff\x12\x14\n" +
	"\x05admin\x18\x05 \x01(\bR\x05admin\"p\n" +
	"\fFinesRequest\x12-\n" +
	"\x05range\x18\x01 \x01(\v2\x17.analytics.v1.DateRangeR\x05range\x12\x19\n" +
	"\bgroup_by\x18\x02 \x01(\tR\agroupBy\x12\x16\n" +
	"\x06public\x18\x03 \x01(\bR\x06public\"o\n" +
	"\vEvacRequest\x12-\n" +
	"\x05range\x18\x01 \x01(\v2\x17.analytics.v1.DateRangeR\x05range\x12\x19\n" +
	"\bgroup_by\x18\x02 \x01(\tR\agroupBy\x12\x16\n" +
	"\x06public\x18\x03 \x01(\bR\x06public\";\n" +
	"\n" +
	"DtpRequest\x12-\n" +
	"\x05range\x18\x01 \x01(\v2\x17.analytics.v1.DateRangeR\x05range\"\xa8\x01\n" +
	"\x0eCompareRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x122\n" +
	"\bperiod_a\x18\x02 \x01(\v2\x17.analytics.v1.DateRangeR\aperiodA\x122\n" +
	"\bperiod_b\x18\x03 \x01(\v2\x17.analytics.v1.DateRangeR\aperiodB\x12\x16\n" +
	"\x06public\x18\x04 \x01(\bR\x06public\"C\n" +
	"\vFilePayload\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"Y\n" +
	"\x12ImportBytesRequest\x12/\n" +
	"\x05files\x18\x01 \x03(\v2\x19.analytics.v1.FilePayloadR\x05files\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"P\n" +
	"\x13ImportBytesResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fsummary_json\x18\x02 \x01(\tR\vsummaryJson\"F\n" +
	"\x12GetForecastRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x18\n" +
	"\ahorizon\x18\x04 \x01(\x05R\ahorizon\"\x87\x02\n" +
	"\x13GetForecastResponse\x128\n" +
	"\vtrain_range\x18\x01 \x01(\v2\x17.analytics.v1.DateRangeR\n" +
	"trainRange\x12\x12\n" +
	"\x04freq\x18\x02 \x01(\tR\x04freq\x127\n" +
	"\bforecast\x18\x03 \x03(\v2\x1b.analytics.v1.ForecastPointR\bforecast\x12=\n" +
	"\flast_history\x18\x04 \x03(\v2\x1a.analytics.v1.HistoryPointR\vlastHistory\x12*\n" +
	"\x04meta\x18\x05 \x01(\v2\x16.analytics.v1.MetaInfoR\x04meta\"q\n" +
	"\rForecastPoint\x12\x0e\n" +
	"\x02ds\x18\x01 \x01(\tR\x02ds\x12\x12\n" +
	"\x04yhat\x18\x02 \x01(\x01R\x04yhat\x12\x1d\n" +
	"\n" +
	"yhat_lower\x18\x03 \x01(\x01R\tyhatLower\x12\x1d\n" +
	"\n" +
	"yhat_upper\x18\x04 \x01(\x01R\tyhatUpper\",\n" +
	"\fHistoryPoint\x12\x0e\n" +
	"\x02ds\x18\x01 \x01(\tR\x02ds\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"{\n" +
	"\bMetaInfo\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x18\n" +
	"\ahorizon\x18\x02 \x01(\x05R\ahorizon\x126\n" +
	"\x02cv\x18\x03 \x01(\v2!.analytics.v1.CrossValidationInfoH\x00R\x02cv\x88\x01\x01B\x05\n" +
	"\x03_cv\"Q\n" +
	"\x13CrossValidationInfo\x12\x10\n" +
	"\x03mae\x18\x01 \x01(\x01R\x03mae\x12\x14\n" +
	"\x05smape\x18\x02 \x01(\x01R\x05smape\x12\x12\n" +
	"\x04mape\x18\x03 \x01(\x01R\x04mape2\xc8\x03\n" +
	"\x10AnalyticsService\x12C\n" +
	"\bGetFines\x12\x1a.analytics.v1.FinesRequest\x1a\x1b.analytics.v1.FinesResponse\x12@\n" +
	"\aGetEvac\x12\x19.analytics.v1.EvacRequest\x1a\x1a.analytics.v1.EvacResponse\x12=\n" +
	"\x06GetDtp\x12\x18.analytics.v1.DtpRequest\x1a\x19.analytics.v1.DtpResponse\x12F\n" +
	"\aCompare\x12\x1c.analytics.v1.CompareRequest\x1a\x1d.analytics.v1.CompareResponse\x12R\n" +
	"\vGetForecast\x12 .analytics.v1.GetForecastRequest\x1a!.analytics.v1.GetForecastResponse\x12R\n" +
	"\vImportBytes\x12 .analytics.v1.ImportBytesRequest\x1a!.analytics.v1.ImportBytesResponseB\x1cZ\x1aproto/analytics; analyticsb\x06proto3"

var (
	file_analitic_proto_rawDescOnce sync.Once
	file_analitic_proto_rawDescData []byte
)

func file_analitic_proto_rawDescGZIP() []byte {
	file_analitic_proto_rawDescOnce.Do(func() {
		file_analitic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analitic_proto_rawDesc), len(file_analitic_proto_rawDesc)))
	})
	return file_analitic_proto_rawDescData
}

var file_analitic_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_analitic_proto_goTypes = []any{
	(*DateRange)(nil),           // 0: analytics.v1.DateRange
	(*Meta)(nil),                // 1: analytics.v1.Meta
	(*Point)(nil),               // 2: analytics.v1.Point
	(*Series)(nil),              // 3: analytics.v1.Series
	(*Aggregates)(nil),          // 4: analytics.v1.Aggregates
	(*KPI)(nil),                 // 5: analytics.v1.KPI
	(*FinesResponse)(nil),       // 6: analytics.v1.FinesResponse
	(*EvacResponse)(nil),        // 7: analytics.v1.EvacResponse
	(*DtpResponse)(nil),         // 8: analytics.v1.DtpResponse
	(*PeriodAgg)(nil),           // 9: analytics.v1.PeriodAgg
	(*Diff)(nil),                // 10: analytics.v1.Diff
	(*CompareResponse)(nil),     // 11: analytics.v1.CompareResponse
	(*FinesRequest)(nil),        // 12: analytics.v1.FinesRequest
	(*EvacRequest)(nil),         // 13: analytics.v1.EvacRequest
	(*DtpRequest)(nil),          // 14: analytics.v1.DtpRequest
	(*CompareRequest)(nil),      // 15: analytics.v1.CompareRequest
	(*FilePayload)(nil),         // 16: analytics.v1.FilePayload
	(*ImportBytesRequest)(nil),  // 17: analytics.v1.ImportBytesRequest
	(*ImportBytesResponse)(nil), // 18: analytics.v1.ImportBytesResponse
	(*GetForecastRequest)(nil),  // 19: analytics.v1.GetForecastRequest
	(*GetForecastResponse)(nil), // 20: analytics.v1.GetForecastResponse
	(*ForecastPoint)(nil),       // 21: analytics.v1.ForecastPoint
	(*HistoryPoint)(nil),        // 22: analytics.v1.HistoryPoint
	(*MetaInfo)(nil),            // 23: analytics.v1.MetaInfo
	(*CrossValidationInfo)(nil), // 24: analytics.v1.CrossValidationInfo
	nil,                         // 25: analytics.v1.Aggregates.SumEntry
	nil,                         // 26: analytics.v1.Aggregates.AvgEntry
	nil,                         // 27: analytics.v1.FinesResponse.SeriesEntry
	nil,                         // 28: analytics.v1.EvacResponse.SeriesEntry
	nil,                         // 29: analytics.v1.DtpResponse.SeriesEntry
}
var file_analitic_proto_depIdxs = []int32{
	2,  // 0: analytics.v1.Series.points:type_name -> analytics.v1.Point
	25, // 1: analytics.v1.Aggregates.sum:type_name -> analytics.v1.Aggregates.SumEntry
	26, // 2: analytics.v1.Aggregates.avg:type_name -> analytics.v1.Aggregates.AvgEntry
	27, // 3: analytics.v1.FinesResponse.series:type_name -> analytics.v1.FinesResponse.SeriesEntry
	4,  // 4: analytics.v1.FinesResponse.aggregates:type_name -> analytics.v1.Aggregates
	5,  // 5: analytics.v1.FinesResponse.kpi:type_name -> analytics.v1.KPI
	1,  // 6: analytics.v1.FinesResponse.meta:type_name -> analytics.v1.Meta
	28, // 7: analytics.v1.EvacResponse.series:type_name -> analytics.v1.EvacResponse.SeriesEntry
	4,  // 8: analytics.v1.EvacResponse.aggregates:type_name -> analytics.v1.Aggregates
	1,  // 9: analytics.v1.EvacResponse.meta:type_name -> analytics.v1.Meta
	29, // 10: analytics.v1.DtpResponse.series:type_name -> analytics.v1.DtpResponse.SeriesEntry
	4,  // 11: analytics.v1.DtpResponse.aggregates:type_name -> analytics.v1.Aggregates
	1,  // 12: analytics.v1.DtpResponse.meta:type_name -> analytics.v1.Meta
	9,  // 13: analytics.v1.CompareResponse.period_a:type_name -> analytics.v1.PeriodAgg
	9,  // 14: analytics.v1.CompareResponse.period_b:type_name -> analytics.v1.PeriodAgg
	10, // 15: analytics.v1.CompareResponse.diff:type_name -> analytics.v1.Diff
	0,  // 16: analytics.v1.FinesRequest.range:type_name -> analytics.v1.DateRange
	0,  // 17: analytics.v1.EvacRequest.range:type_name -> analytics.v1.DateRange
	0,  // 18: analytics.v1.DtpRequest.range:type_name -> analytics.v1.DateRange
	0,  // 19: analytics.v1.CompareRequest.period_a:type_name -> analytics.v1.DateRange
	0,  // 20: analytics.v1.CompareRequest.period_b:type_name -> analytics.v1.DateRange
	16, // 21: analytics.v1.ImportBytesRequest.files:type_name -> analytics.v1.FilePayload
	0,  // 22: analytics.v1.GetForecastResponse.train_range:type_name -> analytics.v1.DateRange
	21, // 23: analytics.v1.GetForecastResponse.forecast:type_name -> analytics.v1.ForecastPoint
	22, // 24: analytics.v1.GetForecastResponse.last_history:type_name -> analytics.v1.HistoryPoint
	23, // 25: analytics.v1.GetForecastResponse.meta:type_name -> analytics.v1.MetaInfo
	24, // 26: analytics.v1.MetaInfo.cv:type_name -> analytics.v1.CrossValidationInfo
	3,  // 27: analytics.v1.FinesResponse.SeriesEntry.value:type_name -> analytics.v1.Series
	3,  // 28: analytics.v1.EvacResponse.SeriesEntry.value:type_name -> analytics.v1.Series
	3,  // 29: analytics.v1.DtpResponse.SeriesEntry.value:type_name -> analytics.v1.Series
	12, // 30: analytics.v1.AnalyticsService.GetFines:input_type -> analytics.v1.FinesRequest
	13, // 31: analytics.v1.AnalyticsService.GetEvac:input_type -> analytics.v1.EvacRequest
	14, // 32: analytics.v1.AnalyticsService.GetDtp:input_type -> analytics.v1.DtpRequest
	15, // 33: analytics.v1.AnalyticsService.Compare:input_type -> analytics.v1.CompareRequest
	19, // 34: analytics.v1.AnalyticsService.GetForecast:input_type -> analytics.v1.GetForecastRequest
	17, // 35: analytics.v1.AnalyticsService.ImportBytes:input_type -> analytics.v1.ImportBytesRequest
	6,  // 36: analytics.v1.AnalyticsService.GetFines:output_type -> analytics.v1.FinesResponse
	7,  // 37: analytics.v1.AnalyticsService.GetEvac:output_type -> analytics.v1.EvacResponse
	8,  // 38: analytics.v1.AnalyticsService.GetDtp:output_type -> analytics.v1.DtpResponse
	11, // 39: analytics.v1.AnalyticsService.Compare:output_type -> analytics.v1.CompareResponse
	20, // 40: analytics.v1.AnalyticsService.GetForecast:output_type -> analytics.v1.GetForecastResponse
	18, // 41: analytics.v1.AnalyticsService.ImportBytes:output_type -> analytics.v1.ImportBytesResponse
	36, // [36:42] is the sub-list for method output_type
	30, // [30:36] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_analitic_proto_init() }
func file_analitic_proto_init() {
	if File_analitic_proto != nil {
		return
	}
	file_analitic_proto_msgTypes[2].OneofWrappers = []any{
		(*Point_Dt)(nil),
		(*Point_Period)(nil),
	}
	file_analitic_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analitic_proto_rawDesc), len(file_analitic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analitic_proto_goTypes,
		DependencyIndexes: file_analitic_proto_depIdxs,
		MessageInfos:      file_analitic_proto_msgTypes,
	}.Build()
	File_analitic_proto = out.File
	file_analitic_proto_goTypes = nil
	file_analitic_proto_depIdxs = nil
}
