FROM python:3.13


ENV PYTHONPATH=/content_service

WORKDIR /content_service

RUN pip install --upgrade pip && \
    pip install poetry


COPY pyproject.toml poetry.lock ./


RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root


COPY .env .env
COPY . .

#RUN alembic revision --autogenerate -m "docker"
#RUN alembic upgrade head

CMD ["python", "server.py"]
